#!/usr/bin/env bash

get_status() {
	STATUS="$(playerctl status)"
	if [[ $STATUS == "Playing" ]]; then
		echo " "
	else
		echo ""
	fi
}

get_volume() {
	echo $(pactl list sinks | grep '^[[:space:]]Volume:' | \
		head -n $(( $SINK + 1 )) | tail -n 1 | \
		sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
}

get_track() {
	ARTIST="$(playerctl metadata artist)"
	SONG="$(playerctl metadata title)"
	echo "$ARTIST - $SONG"
}

if [[ "$1" == "--status" ]]; then
	get_status
fi

if [[ "$1" == "--volume" ]]; then
	get_volume
fi

if [[ "$1" == "--track" ]]; then
	get_track
fi